### ISSUE TITLE
Can you please share the entity and training/testing files

### ISSUE THREAD

**Issue by mdabedr** [tomharting/LOREM#3]
Can you please share the entity and training/testing files?

**Comment by tomh5905** [comment]
Almost all of the datasets that are used are created by other researchers. Therefore, they are not mine to host on this GitHub page. I can refer you to our paper (https://dl.acm.org/doi/10.1145/3366423.3380252) in which you can find links to the datasets that we used. The correct data format for our scripts can be found in the README of this GitHub page.
